---
title: "R Stats Practice"
author: "Ariana Beloiu"
date: "2026-02-19"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(pheatmap)
library(ggplot2) 
library(gplots)
library(dplyr) 
library(tidyr)
```

```{r}
data(iris) 
search()
```
```{r}
library(vegan) 
```

```{r}
thislist <- list("apple", "banana","cherry") 
thislist
```
```{r}
head(iris)
dim(iris) 
str(iris)
```

```{r}
Lista <- list("Laura"=29, "Mark"=30) 
Lista[2] 

Lista$Laura 

Lista["Laura"]
```

```{r}
iris$Sepal.Length #all rows, column Sepal.length 
iris[,3] #all rows, column 3 
iris[c("Sepal.Length","Petal.Width"),] 
iris[2:10,3]
```

```{r}
iris[iris$Petal.Width>1.5,] 
Iris2 <- iris[iris$Petal.Width>1.5,] 
```

```{r}
fit = lm(mpg~wt, data = mtcars) 
fit
```

```{r}
data(mtcars) 
newdata = mtcars[order(mtcars$mpg),] 
newdata = mtcars[order(mtcars$mpg,mtcars$cyl),]  
newdata = mtcars[order(mtcars$mpg,-mtcars$cyl),]
```

```{r}

```

